# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171009_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_users', to='books.Book'),
        ),
    ]
