# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 07:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, max_length=150, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('pageCount', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imageBook')),
                ('pdfFile', models.FileField(blank=True, null=True, upload_to='fileBook')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, null=True, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'slug')]),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_books', to='books.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('title', 'slug')]),
        ),
    ]
