# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-21 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='text',
        ),
    ]
