# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-21 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20171021_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pageOfBook',
            field=models.CharField(max_length=50),
        ),
    ]
